# Generated by Django 4.0.4 on 2022-05-13 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reply_comment_post_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='contnet',
            new_name='content',
        ),
    ]
