# Generated by Django 4.0.4 on 2022-05-13 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_contnet_comment_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='contnet',
            new_name='content',
        ),
    ]
